CREATE DATABASE IF NOT EXISTS crawler;
USE crawler;

CREATE TABLE IF NOT EXISTS pages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url TEXT NOT NULL,
    date DATETIME NOT NULL,
    html LONGTEXT NOT NULL
);
